name: Edge Destroy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Type DESTROY to confirm teardown"
        required: true
        default: ""

env:
  TF_VERSION: 1.5.0
  AWS_REGION: us-east-1
  TF_STATE_KEY: juice-shop/terraform.tfstate

jobs:
  guard:
    name: Confirm Destroy
    runs-on: ubuntu-latest
    steps:
      - name: Validate confirmation input
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "DESTROY" ]; then
            echo "Confirmation mismatch. Type DESTROY to proceed.";
            exit 1;
          fi

  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    needs: guard
    environment: production-approval
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init -input=false -reconfigure \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ env.TF_STATE_KEY }}" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ secrets.TF_STATE_LOCK_TABLE }}" \
            -backend-config="encrypt=true"
        working-directory: terraform

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false
        working-directory: terraform
